### ISSUE TITLE
Transaction conclusion confirmation message

### ISSUE THREAD

**Issue by Hodlatoor** [ubiquity/bounty-bot#238]
I was closing a task which had time but no priority set. I closed it. Reopened, added priority 0 and closed. the bot asked for the wallet address but there's no transaction confirmation.  need to make sure that:
1. There is no logic issue in the process i mentioned above that prevents payment from processing.
2. A confirmation of payout should be automatically generated after it is done. bounty hunters need to be fully aware of when to expect payment.

**Comment by Steveantor** [comment]
Could u attach the issue for further investigation?

**Comment by Hodlatoor** [comment]
https://github.com/ubiquity/grants/issues/4

**Comment by pavlovcik** [comment]
In your specific example, it's a process failure with the bot asking for the wallet address (if it hasn't been registered) when the bounty is considered to be completed. This is fixed with doing this check as soon as the bounty is assigned, leaving plenty of time for the bounty hunter to register their wallet address before completing the bounty. https://github.com/ubiquity/bounty-bot/issues/230#event-8958415707
